# Generated by Django 3.1.3 on 2021-05-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_sort_name', models.CharField(choices=[('ลากิจส่วนตัว', 'ลากิจส่วนตัว'), ('ลาคลอดบุตร', 'ลาคลอดบุตร'), ('ลาป่วย', 'ลาป่วย'), ('ลาพักร้อน', 'ลาพักร้อน'), ('ลาเข้าตรวจรับเลือกทหารหรือเข้ารับการเตรียมพล', 'ลาเข้าตรวจรับเลือกทหารหรือเข้ารับการเตรียมพล'), ('ลาไปช่วยเหลือภรรยาที่คลอดบุตร', 'ลาไปช่วยเหลือภรรยาที่คลอดบุตร'), ('ลาไปศึกษา ฝึกอบรม ปฏิบัติการวิจัย หรือดูงาน', 'ลาไปศึกษา ฝึกอบรม ปฏิบัติการวิจัย หรือดูงาน')], default='ลากิจส่วนตัว', max_length=200)),
                ('leave_department', models.CharField(choices=[('บริหาร', 'บริหาร'), ('จัดซื้อจัดจ้าง', 'จัดซื้อจัดจ้าง'), ('บุคคล', 'บุคคล')], default='บริหาร', max_length=200)),
                ('leave_reason', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('duration1', models.CharField(choices=[('เต็มวัน', 'เต็มวัน'), ('ครึ่งเช้า', 'ครึ่งเช้า'), ('ครึ่งบ่าย', 'ครึ่งบ่าย')], default='เต็มวัน', max_length=100)),
                ('end_date', models.DateField()),
                ('duration2', models.CharField(choices=[('เต็มวัน', 'เต็มวัน'), ('ครึ่งเช้า', 'ครึ่งเช้า'), ('ครึ่งบ่าย', 'ครึ่งบ่าย')], default='เต็มวัน', max_length=100)),
                ('upload', models.FileField(default='', upload_to='leaveapp/file_uploads')),
                ('leave_contact', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'leaveapp_leave_form',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('repassword', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('picture', models.ImageField(default='profile_pics.jpg', upload_to='picture')),
                ('department_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.department_setting')),
                ('leave_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leave_form')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.member')),
            ],
        ),
    ]
