# Generated by Django 3.1.3 on 2021-05-17 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leave_form',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
