# Generated by Django 3.1.3 on 2021-05-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='leaveapp_profile',
        ),
    ]
