# Generated by Django 3.1.3 on 2021-06-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0005_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
