# Generated by Django 3.1.3 on 2021-06-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaveapp', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('repassword', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('picture', models.ImageField(default='profile_pics.jpg', upload_to='picture')),
                ('department_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.department_setting')),
                ('leave_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leave_form')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.member')),
                ('user', models.OneToOneField(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
